include_info_in_instances: false
include_info_in_group_directory: true

groups:
- seed: 42
  instance_number: 10
  instance_group_directory_name: "subproblem_group"

  day:
    strategy: "all_same"
    # day_strategy: "all_random"
    # day_strategy: "repeat_week"

    # week_size: 5
    number: 30
    care_unit_number: 4
    operators_per_care_unit: 4

  operator:
    strategy: "fill"
    # strategy: "random"
    # strategy: "overlap"

    time_slots: 32
    # duration: 16
    # overlap_percentage: 1.0

  service:
    strategy: "pool"
    # strategy: "all_different"

    # care_unit_strategy: "random"
    care_unit_strategy: "balanced"

    pool_size: 30
    duration: {min: 1, max: 6}
  
  patient:
    number: 20
    use_priority: true
    priority: {min: 1, max: 3}
    requests_per_patient: {min: 1, max: 3}