# Elenco di nomi dei soli gruppi da risolvere (inserisci nella lista 'all'
# per analizzare tutti i gruppi)
groups_to_do: ['all']
groups_to_avoid: [] # Elenco dei gruppi di istanze da non risolvere

# Elenco dei grafici da realizzare (inserisci nella lista 'all' per disegnare
# tutti i grafici)
plots: ['all']